#test1
os: linux
language: java
services:
  - docker
cache: bundler
dist: focal
install: skip
jobs:
  include:
    - name: testing
      script:
        - echo "Test started"
        - for i in {1..10}; do echo "still running… minute $i/10"; sleep 60; done
        - echo "Test finished"
after_success:
  - echo passed
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
